[package]
name = "qb-floccus"
version = "0.12.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"] }
roxmltree = "0.19"
quick-xml = "0.31"
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
httpdate = "1.0"
toml = "0.8"
